# **📌 PROJECT 1 — Apple iPhone Weekly Temperature Analysis**

**Apple records CPU temperature of iPhones every hour for 24 hours:**

# Tasks:

Convert to NumPy array

Slice morning temps (5am–11am)

Slice evening temps (5pm–11pm)

Extract temps above 42°C

Count overheating hours

In [ ]:
#Apple records CPU temperature of iPhones every hour for 24 hours:

temps = [
38.1, 39.5, 40.2, 41.1, 42.3, 43.0, 44.4, 45.1,
41.3, 39.9, 38.7, 36.8, 35.8, 34.5, 33.8, 34.4,
36.2, 37.5, 38.9, 40.1, 41.0, 42.5, 44.0, 45.3
]

**1. Convert to NumPy**

In [3]:
import numpy as np
temps_array = np.array(temps)
temps_array

array([38.1, 39.5, 40.2, 41.1, 42.3, 43. , 44.4, 45.1, 41.3, 39.9, 38.7,
       36.8, 35.8, 34.5, 33.8, 34.4, 36.2, 37.5, 38.9, 40.1, 41. , 42.5,
       44. , 45.3])

**2. Morning temps (5am–11am)**

In [5]:
morning = temps_array[5:12]
morning


array([43. , 44.4, 45.1, 41.3, 39.9, 38.7, 36.8])

**3. Evening temps (5pm–11pm)**

In [6]:
evening = temps_array[17:24]
evening

array([37.5, 38.9, 40.1, 41. , 42.5, 44. , 45.3])

**Extract temps above 42°C**

In [ ]:
hot = temps_array[temps_array>42]
hot

array([42.3, 43. , 44.4, 45.1, 42.5, 44. , 45.3])

**5. Count overheating**

In [10]:
count_overheating = np.sum(temps_array>42)
count_overheating

np.int64(7)