# **📌 PROJECT 3 — McDonald’s Mini Billing System**

**McDonald's menu prices:**

In [43]:
import numpy as np
prices = np.array([120,80,150,200,50])
# Items: Burger, Fries, Shake, Meal, Coke
order = [0,1,4,3]

**1. Ordered item prices**

In [44]:
items = prices[order]
items

# prices[[0,1,4,3]] #Alternative

array([120,  80,  50, 200])

**2. Slice first 3 items**

In [45]:
first_3 = prices[:3]
first_3

array([120,  80, 150])

**3. Extract costly items from Order (>100)**

In [46]:
costly = items[items>=100]
costly

array([120, 200])

**4. Extract costly items from Menu (>100)**

In [47]:
costly = prices[prices>100]
costly

array([120, 150, 200])

**5. Calculate bill**

In [41]:
total_bill = np.sum(items)
print(total_bill)

450


**5. Discount check**

In [48]:
if total_bill > 400:
    print("Discount Allow")

else:
    print("No Discount")

Discount Allow
