# **📌 PROJECT 2 — Netflix Watch-Time Analyzer (Basic Version)**

**Dataset: watch-time in minutes for 14 days:**

# **Tasks**

Convert to NumPy

Extract weekend (last 2 days)

Extract binge-watching days > 100 mins

Extract low-activity days < 40 mins

Find average weekday watch time

In [2]:
watch = [45, 60, 55, 120, 150, 30, 40, 75, 100, 90, 50, 30, 20, 200]

**Convert to NumPy**

In [4]:
import numpy as np
watch_arr = np.array(watch)
type(watch_arr)

numpy.ndarray

**Extract weekend (last 2 days)**

In [ ]:
weekend = watch_arr[-2:]
weekend

array([ 20, 200])

**Extract binge-watching days > 100 mins**

In [12]:
bing = watch_arr[watch_arr>=100]
bing

array([120, 150, 100, 200])

**Extract low-activity days < 40 mins**

In [13]:
low = watch_arr[watch_arr<=40]
low

array([30, 40, 30, 20])

**Find average weekday watch time**

In [21]:
watch_time_avg = np.mean(watch_arr[:12])
print(watch_time_avg)
print(round(watch_time_avg,2))

70.41666666666667
70.42
