In [2]:
# Q9 — 1D, 2D, 3D arrays
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a3 = np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]]])


In [4]:
# Q10 — zeros

arr = np.zeros((5,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Q11 — ones + scalar

# a = np.ones((3,3))      # Initial approach
a = np.ones((3,3)) * 10  # Alternative approach
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Q12 — arange

np.arange(1,5)
np.arange(1,5)*3
np.arange(1,5)*3 + 2
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

In [13]:
# Q13 — linspace

arr = np.linspace(0,1,3)
arr

array([0. , 0.5, 1. ])

In [17]:
# Q14 — dtype / shape / size

scores = np.array([56,78,90,85,45,65,89,91])
scores.dtype
# scores.shape
# scores.size

dtype('int64')

In [23]:
# Q15 — astype(int)

arr = np.array([3.5,4.7,6.8])
new = arr.astype(int)
new

array([3, 4, 6])

In [26]:
# Q16 — identity matrix

i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])