In [4]:
import numpy as np

In [8]:
# Q17 — slices

data = np.array([10,20,30,40,50,60,70])
first3 = data[:3]
last2 = data[-2:]
middle = data[2:5]
print("First 3 elements:", first3)
print("Last 2 elements:", last2)
print("Middle elements (index 2 to 4):", middle)

First 3 elements: [10 20 30]
Last 2 elements: [60 70]
Middle elements (index 2 to 4): [30 40 50]


In [9]:
# Q18 — reverse

data = np.array([10,20,30,40,50])
reversed_data = data[::-1]
reversed_data

array([50, 40, 30, 20, 10])

In [10]:
# Q19 — 2D matrix slicing

m = np.array([[10,20,30],[40,50,60],[70,80,90]])

row1 = m[0]
col2 = m[:,1]
sub = m[1:3, 1:3]
print("First row:", row1)
print("Second column:", col2)
print("Sub-matrix (rows 1-2, cols 1-2):", sub)

First row: [10 20 30]
Second column: [20 50 80]
Sub-matrix (rows 1-2, cols 1-2): [[50 60]
 [80 90]]


In [12]:
# Q20 — boolean mask

ages = np.array([15,22,17,45,33,28,12])

adults = ages[ages >= 18]
print(adults)
minor = ages[ages < 18]
print(minor)
mid = ages[(ages>=18) & (ages<=30)]
print(mid)

[22 45 33 28]
[15 17 12]
[22 28]


In [ ]:
# Q21 — fancy indexing

arr = np.array([100,200,300,400,500])
res = arr[[0,2,4]] # fancy indexing to get elements at index 0, 2, and 4
res

array([100, 300, 500])

In [14]:
# Q22 — modify using fancy indexing

arr = np.array([10,20,30,40,50])
arr[[1,3]] +=100
arr

array([ 10, 120,  30, 140,  50])