In [7]:
import numpy as np

In [13]:
# ❓ Q1 — What is a VIEW? What is a COPY?

arr = np.array([10,20,30,40])

In [17]:
v = arr[:2]  # VIEW
v[0] = 99
arr  # original array is affected


array([99, 20, 30, 40])

In [16]:
v

array([99, 20])

In [19]:
c = arr.copy()  # COPY
c[0] = 55

In [20]:
c

array([55, 20, 30, 40])

In [ ]:
arr 

array([99, 20, 30, 40])

In [ ]:
# ❓ Q2 — Proof that View shares memory

a = np.array([1,2,3,4])
b = a[1:3]  # VIEW
b[0] = 99
a # original array is affected

array([ 1, 99,  3,  4])

In [ ]:
# ❓ Q3 — Proof that Copy doesn’t share memory
# Copy → independent.

a = np.array([5,10,15])
b = a.copy()
b[1] = 76

a # original array is NOT affected
# b 

array([ 5, 76, 15])

In [29]:
# ❓ Q4 — Check view vs copy using may_share_memory()
from numpy import may_share_memory

a = np.arange(1,11)
b = a[1:3] # VIEW
c = a.copy() # COPY

print(may_share_memory(a,b))  # True
print(may_share_memory(a,c))  # False

True
False


In [32]:
# ❓ Q5 — Change slice in 2D array affects original?

m = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = m[:,1] # VIEW
v[0] = 99
m



array([[ 1, 99,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [33]:
# ❓ Q6 — Create submatrix as view

m = np.array([
 [10,20,30],
 [40,50,60],
 [70,80,90]
])

subm = m[1:3,1:3]  # VIEW
subm

array([[50, 60],
       [80, 90]])

In [ ]:
# ❓ Q7 — When does NumPy FORCE a copy?

x = np.array([1,2,3])
y = x.astype(float)  # FORCE cop
y
# x

array([1, 2, 3])

In [ ]:
# ❓ Q8 — Force copy of view

a = np.array([10,20,30,40])

v = a[3:]  # VIEW
safe = v.copy()  # FORCE COPY
safe[0] = 99
safe
# v

array([40])