In [2]:
import numpy as np

In [3]:
# ❓ Q9 — Simple 1D iteration

arr = np.array([10,20,30,40])
for x in arr:
    print(x)

10
20
30
40


In [11]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
for x in arr:
    print(x)

[10 20 30 40]
[50 60 70 80]


In [8]:
# ❓ Q10 — Row-by-row iteration of 2D array

m = np.array([[1,2],[3,4],[5,6]])

for row in m:
    # for num in row:
    #     print(num)
    print(row)

[1 2]
[3 4]
[5 6]


In [ ]:
# ❓ Q11 — Iterate ALL elements in 2D using .flat
for x in m.flat:  # Not need for nested loops
    print(x)

1
2
3
4
5
6


In [ ]:
# ❓ Q12 — Modify all elements using nditer() 

m = np.array([[1,2],[3,4],[5,6]])

for x in np.nditer(m, op_flags=["readwrite"]):
    x[...] = x + 2

m

array([[3, 4],
       [5, 6],
       [7, 8]])

array([[3, 4],
       [5, 6],
       [7, 8]])

In [17]:
# ❓ Q13 — Use ndenumerate() to get index + value

m = np.array([[10,20],[30,40]])
for index, x in np.ndenumerate(m):
    print(index, x)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


In [18]:
# ❓ Q14 — Iterate 3D array element-wise

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in arr3.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [19]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in arr3:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
"""     
❓ Q15 — Proof that iteration in NumPy is slower than vectorization

Explain why loops are bad.

✔ SOLUTION

Because NumPy = C-optimized vector ops.
Loop = Python-level slow.

"""