In [2]:
import numpy as np
import random

In [3]:
# ❓ Q16 — Generate 10 random floats (0–1)

np.random.rand(10)

array([0.27665903, 0.26450121, 0.91737801, 0.2955545 , 0.93507279,
       0.23566274, 0.54909246, 0.82285938, 0.77885755, 0.92509512])

In [4]:
# ❓ Q17 — Generate random integers 50–100 (size=20)

np.random.randint(50,101,20)

array([56, 96, 62, 81, 50, 66, 75, 58, 61, 70, 63, 93, 51, 73, 62, 83, 77,
       81, 59, 51], dtype=int32)

In [22]:
# ❓ Q18 — Generate normal distribution (mean=0, std=1)

a = np.random.randn(10)


In [34]:
# ❓ Q19 — Shuffle array IN-PLACE

arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[4 9 8 2 5 3 7 0 6 1]
[4 9 8 2 5 3 7 0 6 1]


In [35]:
# ❓ Q20 — Create shuffled copy (original safe)

arr = np.arange(10)
print(arr)

new = np.random.permutation(arr)
print(new)

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[6 2 1 9 0 3 4 7 8 5]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
# ❓ Q21 — Random choice from list

cities = np.array(["Delhi","Mumbai","Pune","Goa"])

np.random.choice(cities, size=5)

array(['Goa', 'Pune', 'Delhi', 'Goa', 'Delhi'], dtype='<U6')

In [43]:
# ❓ Q22 — Random sample WITHOUT replacement

np.random.choice(np.arange(16), size=3,replace=False)

array([ 9, 15, 14])

In [50]:
# ❓ Q23 — Set seed for reproducible results
# ❓ Q24 — Generate 2D random matrix (3×4)

np.random.seed(42)
np.random.randint(3,100,4)

array([54, 95, 17, 74], dtype=int32)