In [17]:
import numpy as np

**Tasks**

✓ Create a slice (view) of orders 10–20

✓ Create a copy of orders 30–40

✓ Prove view modifies original

✓ Prove copy does NOT

✓ Use may_share_memory() to validate

In [18]:
orders = np.arange(1, 51)  # 50 orders ID
orders

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

**🎯 STEP 2 — SLICE (view) of orders 10–20**

In [19]:
view_order = orders[10:21]
view_order

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

**🎯 STEP 3 — COPY of orders 30–40**

In [20]:
copy_order = orders[30:41].copy()
copy_order

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41])

**🎯 STEP 4 — Modify the view**

In [21]:
view_order[0] = 9999
view_order

array([9999,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21])

In [22]:
orders

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10, 9999,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50])

**🎯 STEP 5 — Modify the copy**

In [23]:
copy_order[1] = 10000
copy_order

array([   31, 10000,    33,    34,    35,    36,    37,    38,    39,
          40,    41])

In [24]:
orders

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10, 9999,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50])

**🎯 STEP 6 — Verify using may_share_memory()**

In [25]:
print(np.may_share_memory(orders,view_order))
print(np.may_share_memory(orders,copy_order))

True
False
