In [33]:
import numpy as np

**Tasks**

✓ Generate base fares

✓ Generate surge multipliers

✓ Apply broadcasting → final = base * surge

✓ Find expensive rides (>400)

✓ Iterate & print index + fare using ndenumerate()


**Dataset Generation**

In [34]:
# Base fare per ride:
base = np.random.randint(100, 300, 20)
base

array([169, 182, 285, 111, 155, 287, 245, 131, 172, 133, 144, 204, 138,
       274, 148, 263, 284, 231, 139, 114], dtype=int32)

In [35]:
# Surge multipliers:
surge = np.random.uniform(1.0, 2.5, 20)
surge

array([1.07251348, 2.07356601, 1.60847671, 1.09197419, 2.28757395,
       1.79852621, 2.01510586, 1.53159654, 2.39997311, 1.77463281,
       1.2442587 , 2.49024621, 1.22955275, 1.89523463, 1.02132652,
       2.28439237, 1.79617712, 2.40636245, 1.10474097, 1.51268775])

**Apply broadcasting**

In [36]:
final = base * surge
final

array([181.25477785, 377.38901422, 458.41586275, 121.20913472,
       354.57396177, 516.17702106, 493.70093586, 200.63914642,
       412.79537438, 236.02616342, 179.17325256, 508.01022774,
       169.67827919, 519.29428872, 151.15632536, 600.79519264,
       510.11430073, 555.86972503, 153.55899487, 172.44640319])

**Find expensive rides (>400)**

In [37]:
expensive_ride = final[final>400]
expensive_ride

array([458.41586275, 516.17702106, 493.70093586, 412.79537438,
       508.01022774, 519.29428872, 600.79519264, 510.11430073,
       555.86972503])

**🎯 STEP 5 — Print each ride (index + fare)**

In [38]:
for index, fare in np.ndenumerate(final):
    print(index[0],round(fare,2))

0 181.25
1 377.39
2 458.42
3 121.21
4 354.57
5 516.18
6 493.7
7 200.64
8 412.8
9 236.03
10 179.17
11 508.01
12 169.68
13 519.29
14 151.16
15 600.8
16 510.11
17 555.87
18 153.56
19 172.45
