**Task Dataset Generation:**

Generate 100 videos

Each has:

views (random 10K–500K)

likes (random 500–30K)

comments (random 50–1K)

**Tasks**

✓ Generate 3 random arrays

✓ Combine into matrix → (100,3)

✓ Iterate row-by-row

✓ Compute like ratio = likes / views

✓ Filter videos with like ratio > 5%

**🎯 STEP 1 — 100 Random Videos**

In [12]:

import numpy as np

np.random.seed(10)

views = np.random.randint(10000,500001,100)
like = np.random.randint(500,30001,100)
comments = np.random.randint(50,1001,100)



**🎯 STEP 2 — Make Data matrix  (100 × 3)**

In [13]:
data = np.column_stack((views, like, comments))
data

array([[355353,  19529,    305],
       [246669,  27786,    927],
       [366879,  26623,    592],
       [453712,   7268,    173],
       [103553,  21760,    715],
       [115595,  15568,    256],
       [ 19372,   5076,    515],
       [413417,  25138,    263],
       [309741,   2026,     63],
       [290048,  15021,    731],
       [118445,  25061,    979],
       [288385,  14403,    566],
       [446218,  19296,    777],
       [150296,  17116,    400],
       [281433,   4126,    590],
       [196624,  19681,    601],
       [237818,  23341,    397],
       [366392,   5343,    153],
       [479494,  19750,    827],
       [255156,  19489,    313],
       [450691,  29133,    200],
       [113952,  15549,     82],
       [325748,  24729,    821],
       [190463,  15476,    571],
       [ 61595,  17798,    230],
       [470854,  15371,    758],
       [308328,   2039,    208],
       [ 17290,  19729,    504],
       [436558,   8452,    426],
       [435505,   1862,    934],
       [33

**🎯 STEP 3 — Iterate row-by-row**

In [14]:
for rows in data:
    pass  # just demonstration

**🎯 STEP 4 — Find Like Ratio**

In [15]:
like_ratio = like/views
like_ratio

array([0.05495662, 0.11264488, 0.07256616, 0.01601897, 0.21013394,
       0.13467711, 0.26202767, 0.06080543, 0.00654095, 0.05178798,
       0.21158344, 0.04994365, 0.04324344, 0.11388194, 0.01466068,
       0.1000946 , 0.09814648, 0.01458274, 0.04118925, 0.07638072,
       0.06464074, 0.13645219, 0.07591451, 0.08125463, 0.28895203,
       0.03264494, 0.00661309, 1.1410642 , 0.01936054, 0.0042755 ,
       0.04894148, 0.05114099, 0.50596343, 0.27134034, 0.06095869,
       0.06220343, 0.00839188, 0.0367443 , 0.02104449, 0.02099899,
       0.03962502, 0.03876742, 0.12772027, 0.13719258, 0.03075939,
       0.22328475, 0.10872857, 0.17808815, 0.10476875, 0.03190813,
       0.02263568, 0.23377061, 0.01094525, 0.25177084, 0.56710671,
       0.10405644, 0.01253092, 0.08152027, 0.12568856, 0.09608344,
       0.03822766, 0.10733603, 0.00294034, 0.00998447, 0.11947121,
       0.06986134, 0.91011892, 0.10656505, 0.02668025, 0.08044826,
       0.00639068, 0.06379191, 0.06120072, 0.22520947, 0.13956

**🎯 STEP 5 — Filter videos Where LIKE RATIO > 5%**

In [18]:
best_videos = data[like_ratio>0.05]
best_videos

array([[355353,  19529,    305],
       [246669,  27786,    927],
       [366879,  26623,    592],
       [103553,  21760,    715],
       [115595,  15568,    256],
       [ 19372,   5076,    515],
       [413417,  25138,    263],
       [290048,  15021,    731],
       [118445,  25061,    979],
       [150296,  17116,    400],
       [196624,  19681,    601],
       [237818,  23341,    397],
       [255156,  19489,    313],
       [450691,  29133,    200],
       [113952,  15549,     82],
       [325748,  24729,    821],
       [190463,  15476,    571],
       [ 61595,  17798,    230],
       [ 17290,  19729,    504],
       [231028,  11815,    848],
       [ 35550,  17987,    187],
       [ 89537,  24295,    308],
       [222659,  13573,    556],
       [480070,  29862,    677],
       [223645,  28564,    390],
       [177772,  24389,    994],
       [ 71214,  15901,    724],
       [270766,  29440,    218],
       [149353,  26598,     96],
       [242076,  25362,    978],
       [ 4