In [142]:
import numpy as np

In [143]:
# Q26. Create arrays using zeros, ones, arange, linspace, eye, and explain when each is used.

a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [144]:
b = np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [145]:
c = np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
d = np.linspace(1,5,100)
d

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [147]:
# ⭐ Use in Linear Algebra, Matrix Multiplication, ML algorithms, I = identity transform.
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [148]:
# Q27. Convert Python lists to NumPy arrays and explain performance difference.

lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(arr)
print(type(arr))

# example?

lst = [1,2,3]
aa = lst * 2  # BAD – repeats: [1,2,3,1,2,3]
print(aa)

arr = np.array([1,2,3])
bb = arr * 2  # GOOD – multiplies each element: [2 4 6]
print(bb)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 1, 2, 3]
[2 4 6]


In [149]:
# Q28. Check dtype, ndim, shape, size for a given array.

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("dtype :", arr.dtype)
print("ndim  :", arr.ndim)
print("shape :", arr.shape)
print("size  :", arr.size)

dtype : int64
ndim  : 2
shape : (2, 3)
size  : 6


In [150]:
# Q29. Convert float array → int using .astype() and explain truncation.

arr = np.array([1.2, 3.9, 7.7, -2.4])
arr_int = arr.astype(int)

print(arr)
print(arr_int)

[ 1.2  3.9  7.7 -2.4]
[ 1  3  7 -2]


In [151]:
# Q30. Create a 3D array and explain indexing differences from 2D.

a = np.array([[[1,2,3],[4,5,6]]])
a.ndim

b = np.array([[1,2,3],[4,5,6]])
b.ndim

2

In [152]:
# Q31. Extract even-index rows from a matrix.

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

even = arr[::2]
print(even)



[[10 20 30]
 [70 80 90]]


In [153]:
# Q32. Reverse columns of a 2D array.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

rev = arr[:,::-1]
rev


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [154]:
# Q33. Extract a 2×3 submatrix from a 4×4 matrix.


A = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

sub = A[2:4, 1:4]
sub



array([[10, 11, 12],
       [14, 15, 16]])

In [155]:
# Q34. Use boolean mask to filter values > mean.

arr = np.array([10, 25, 5, 40, 18, 32])

mean = arr.mean()
mean

np.float64(21.666666666666668)

In [156]:
mask = [arr>mean]
mask

[array([False,  True, False,  True, False,  True])]

In [157]:
# Q35. Fancy indexing: pick indices [0,2,5,7] from a 1D array.


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

result = arr[[0, 2, 5, 7]]

print(result)

[10 30 60 80]


In [158]:
# Q36. Add, subtract, multiply two arrays element-wise.

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

add = a + b
sub = a - b
mul = a * b

print(f"ADD: {add}")
print(f"Sub: {sub}")
print(f"MUL: {mul}")

ADD: [11 22 33 44]
Sub: [ -9 -18 -27 -36]
MUL: [ 10  40  90 160]


In [159]:
# Q37. Apply percentage discount to an array using broadcasting.

prices = np.array([100, 250, 500, 1200])

discount = 10  # 10% discount

# broadcasting: discount/100 applies to every element automatically
final_price = prices - (prices * (discount / 100))
print(final_price)

[  90.  225.  450. 1080.]


In [160]:
# Q38. Standardize array: (x - mean) / std.

x = np.array([10, 20, 30, 40, 50])

mean = x.mean()
std = x.std()

stand = (x - mean)/ std


print("Mean:", mean)
print("Std :", std)
print("Standardized:", stand)

Mean: 30.0
Std : 14.142135623730951
Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [161]:
# Q39. Row-wise and column-wise summation.

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_sum = a.sum(axis=1)
col_sum = a.sum(axis=0)

print("Matrix:\n", a)
print("Row-wise Sum :", row_sum)
print("Column-wise Sum :", col_sum)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise Sum : [ 6 15 24]
Column-wise Sum : [12 15 18]


In [162]:
# Q40. Normalize matrix column-wise.

X = np.array([
    [1,  5, 10],
    [2,  7, 20],
    [3,  9, 30],
    [4, 11, 40]
])

col_min = X.min(axis=0)
col_max = X.max(axis=0)

norm_col = (X - col_min) / (col_max - col_min)
print(norm_col)

[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


In [163]:
# Q41. Reshape (12,) → (3,4).

a = np.arange(12)
b = a.reshape(3,4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [164]:
# Q42. Flatten 2D into 1D and compare flatten vs ravel.

a = np.array([[1, 2, 3],
              [4, 5, 6]])

flat1 = a.flatten()
print(flat1)

[1 2 3 4 5 6]


In [165]:
flat2 = a.ravel()
print(flat2)

[1 2 3 4 5 6]


In [166]:
a[0,0] = 99
print(flat1)
print(flat2)

[1 2 3 4 5 6]
[99  2  3  4  5  6]


In [167]:
# Q43. Concatenate two matrices vertically and horizontally.

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

H = np.hstack((A,B))
print(H)

V = np.vstack((A,B))
print(V)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [169]:
print(np.concatenate((A,B), axis = 1))
print(np.concatenate((A,B), axis = 0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [170]:
# Q44. Split array into 3 equal parts.

arr = np.arange(9)
parts = np.split(arr,3)
print(parts)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [171]:
# Q45. Transpose a matrix.

a = np.array([[1, 2, 3],
              [4, 5, 6]])

T = a.T

print(T)

[[1 4]
 [2 5]
 [3 6]]


In [172]:
# Q46. Show how modifying a slice affects original array.

a = np.array([10, 20, 30, 40, 50])

s = a[2:4]
s[0] = 99
print(s)
print(a)

[99 40]
[10 20 99 40 50]


In [173]:
# Q47. Prove copy() creates a new memory block.

from numpy import may_share_memory

a = np.array([10, 20, 30])

b = a[:]
c = a.copy()

b[0] = 999
c[0] = 999

print("Original a:", a)
print("View b:", b)
print(may_share_memory(a,b))
print("Copy c:", c)
print(may_share_memory(a,c))



Original a: [999  20  30]
View b: [999  20  30]
True
Copy c: [999  20  30]
False


In [174]:
# Q49. Explain why dtype conversion always creates copy.

a = np.array([1,2,3], dtype=np.int32)
b = a.astype(np.float64)

print(a is b)  # False → different object
print(a.base, b.base)  # different memory


False
None None


In [175]:
# Q50. Create a non-contiguous view using slicing.

arr = np.arange(10)        # [0 1 2 3 4 5 6 7 8 9]

view = arr[::2]            # take every 2nd element (non-contiguous view)

print("Original:", arr)
print("View:", view)
print("Is view contiguous?", view.flags['C_CONTIGUOUS'])
print("Is view a view?", view.base is arr)


Original: [0 1 2 3 4 5 6 7 8 9]
View: [0 2 4 6 8]
Is view contiguous? False
Is view a view? True


In [176]:
# Q51. Iterate over 2D matrix using row-by-row.



A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

for row in A:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [177]:
# ✅ Q52. Iterate using ndenumerate() and print index + value

A = np.array([[10,20,30],
              [40,50,60]])

for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [180]:
# ✅ Q53. Generate random integers (size 1000) and compute histogram

data = np.random.randint(1,11,size=1000)
h,b = np.histogram(data, bins=10)
print("Histogram counts:", h)
print("Bins:", b)

Histogram counts: [102  98  97  89  96 121  99  95 102 101]
Bins: [ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [182]:
# ✅ Q54. Shuffle an array in place vs get shuffled copy

arr = np.arange(10)

np.random.shuffle(arr)
print("Shuffled in place:", arr)

arr2 = np.arange(10)
s_c = np.random.permutation(arr2)
print("Shuffled copy:", s_c)
print("Original arr2:", arr2)

Shuffled in place: [8 2 5 9 3 4 1 6 7 0]
Shuffled copy: [6 9 3 1 5 2 4 0 8 7]
Original arr2: [0 1 2 3 4 5 6 7 8 9]


In [184]:
# ✅ Q55. Simulate normal distribution and compute 95% confidence interval

data = np.random.normal(loc=50, scale=10, size=1000)

mean = np.mean(data)
std = np.std(data)

lower = mean - 1.96 * std
upper = mean + 1.96 * std

print("Mean:", mean)
print("Std:", std)
print("95% CI:", (lower, upper))


Mean: 49.91490704349952
Std: 10.192606770172231
95% CI: (np.float64(29.937397773961944), np.float64(69.89241631303709))
