In [30]:
import numpy as np

In [31]:
""" 
Task:

Add

Subtract

Multiply

Divide

"""


a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Addition
add = a +b
print("Addition:", add)
# Subtraction
sub = a - b 
print("Subtraction:", sub)
# Multiplication    
mul = a * b
print("Multiplication:", mul)
# Division
div = a / b
print("Division:", div)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [32]:
# ❓ Q2 — Scalar operations

arr = np.array([5, 10, 15, 20])

# Add 10 to each element
add_scalar = arr + 10
print("Add 10:", add_scalar)
# Subtract 5 from each element
sub_scalar = arr - 5    
print("Subtract 5:", sub_scalar)
# Multiply each element by 3
mul_scalar = arr * 3
print("Multiply by 3:", mul_scalar)
# Divide each element by 2 
div_scalar = arr / 2
print("Divide by 2:", div_scalar)

Add 10: [15 20 25 30]
Subtract 5: [ 0  5 10 15]
Multiply by 3: [15 30 45 60]
Divide by 2: [ 2.5  5.   7.5 10. ]


In [33]:
# ❓ Q3 — Comparison Operations

"""   
Find:

scores >= 50

scores < 40

scores == 90

"""


marks = np.array([45, 67, 89, 23, 78, 90, 56])

# Greater than or equal to 50
great = marks >= 50
# great = marks[marks >= 50]
print("Scores >= 50:", great)
# Less than 40
less = marks < 40
print("Scores < 40:", less)
# Equal to 90
equal = marks == 90
print("Scores == 90:", equal)


Scores >= 50: [False  True  True False  True  True  True]
Scores < 40: [False False False  True False False False]
Scores == 90: [False False False False False  True False]


In [34]:
# ❓ Q4 — Logical AND / OR

"""   
Find numbers:

between 25 and 75

< 30 OR > 80

"""

arr = np.array([12, 25, 30, 50, 75, 90])

# Between 25 and 75
mid = arr[(arr >= 25) & (arr <= 75)]
print(mid)
side = arr[(arr < 30) | (arr >80)]
print(side)

[25 30 50 75]
[12 25 90]


In [35]:
# ❓ Q5 — Aggregate Functions (sum, mean, min, max)

sales = np.array([200, 300, 250, 400, 350])

total_sales = np.sum(sales)
print("Total Sales:", total_sales)
average_sales = np.mean(sales)
print("Average Sales:", average_sales)
min_sales = np.min(sales)
print("Minimum Sales:", min_sales)
max_sales = np.max(sales)
print("Maximum Sales:", max_sales)

Total Sales: 1500
Average Sales: 300.0
Minimum Sales: 200
Maximum Sales: 400


In [36]:
# ❓ Q6 — Axis-based operations

m = np.array([
 [10,20,30],
 [40,50,60],
 [70,80,90]
])

a = np.sum(m,axis=0)  # Column-wise sum
b = np.sum(m,axis=1)  # Row-wise sum

print("Column-wise sum:", a)
print("Row-wise sum:", b)
m.sum(axis=0)  # Column-wise sum
m.sum(axis=1)  # Row-wise sum



Column-wise sum: [120 150 180]
Row-wise sum: [ 60 150 240]


array([ 60, 150, 240])

In [37]:
# ❓ Q7 — Broadcasting Magic

prices = np.array([100, 200, 300])
tax = np.array([5])

final_prices = prices + tax
print("Final Prices with Tax:", final_prices)

Final Prices with Tax: [105 205 305]


In [38]:
# ❓ Q8 — incompatible broadcasting (error)

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20])


'''    
EXPLANATION

Shapes:

a → (2,3)

b → (2,)

Broadcasting rule:
Last dimension match hona chahiye.

3 != 2 → ERROR
Simple.

'''

'    \nEXPLANATION\n\nShapes:\n\na → (2,3)\n\nb → (2,)\n\nBroadcasting rule:\nLast dimension match hona chahiye.\n\n3 != 2 → ERROR\nSimple.\n\n'

In [39]:
# ❓ Q9 — Normalize array

x = np.array([5,10,15])

# Normalized value = x / max(x)
x/x.max()

array([0.33333333, 0.66666667, 1.        ])

In [ ]:
# ❓ Q10 — Standardize array

# (z = (x - mean) / std)
(x - x.mean()) / x.std()

array([-1.22474487,  0.        ,  1.22474487])