In [1]:
import numpy as np

In [2]:
# ❓ Q17 — concatenate 1D

a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [3]:
# ❓ Q18 — vertical stack

x = np.array([1,2,3])
y = np.array([4,5,6])
np.vstack((x,y))  # vertical stack

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# ❓ Q19 — horizontal stack

x = np.array([1,2,3])
y = np.array([4,5,6])
np.hstack((x,y))  # horizontal stack

array([1, 2, 3, 4, 5, 6])

In [7]:
# ❓ Q20 — split array

arr = np.array([10,20,30,40,50,60])
np.split(arr,3)


[array([10, 20]), array([30, 40]), array([50, 60])]

In [ ]:
# ❓ Q21 — hsplit

m = np.array([[1,2,3],[4,5,6]])
np.hsplit(m,3)  # split into 3 arrays horizontally

# ❓ Q22 — vsplit
np.vsplit(m,2)  # split into 2 arrays vertically

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]