In [2]:
import numpy as np

In [3]:
# ❓ Q11 — reshape 1D → 2D

arr = np.arange(1,13)

arr.reshape(3,4)  # 3 rows, 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# ❓ Q12 — reshape 1D → 3D

np.arange(1,9)
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# ❓ Q13 — flatten array

m = np.array([[1,2,3],[4,5,6]])
m.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
# ❓ Q14 — resize array

x = np.array([1,2,3])
np.resize(x, 6)


array([1, 2, 3, 1, 2, 3])

In [19]:
# ❓ Q15 — transpose matrix

m = np.array([[1,2],[3,4],[5,6]])
m.T

array([[1, 3, 5],
       [2, 4, 6]])

In [23]:
# ❓ Q16 — reshape using -1

arr = np.arange(12)
arr.reshape(2,-1)  # 2 rows, automatically calculate columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])