In [75]:
import numpy as np

Tasks:

Apply 10% discount using broadcasting

Extract cheap (<300) and costly (≥300) items

Concatenate both lists

Reshape final list into 2-column format for dashboar

In [76]:
prices = np.array([200,300,150,400,500,600])
discount = np.array([10])  # flat 10%

**1. Apply discount**

In [77]:
final = prices * 0.90
print(final)

[180. 270. 135. 360. 450. 540.]


**2. Separate cheap (<300) and costly (>=300)**

In [78]:
cheap = final[final < 300]
costly = final[final >= 300]


print("Cheap items:", cheap)
print("Costly items:", costly)

Cheap items: [180. 270. 135.]
Costly items: [360. 450. 540.]


**3. Combine both into final list**

In [79]:
combined = np.concatenate((cheap,costly))
combined

array([180., 270., 135., 360., 450., 540.])

**4. Reshape into 2-column dashboard**

In [80]:
dashboard = combined.reshape(-1,2)
dashboard

array([[180., 270.],
       [135., 360.],
       [450., 540.]])