Tasks:

Reshape into (4,3)

Extract binge sessions (>100)

Split dataset into first half & second half

Concatenate reversed sessions with original

In [1]:
import numpy as np

In [2]:
#Dataset

sessions = np.array([45,60,30,200,150,20,90,120,30,15,75,180])

**1. Reshape into 4 weeks × 3 sessions**

In [3]:
weeks = sessions.reshape(4,3)
print(weeks)

[[ 45  60  30]
 [200 150  20]
 [ 90 120  30]
 [ 15  75 180]]


**2. Find binge (>100)**

In [4]:
binge = sessions[sessions>=100]
print("Binge sessions (>100 mins):", binge)

Binge sessions (>100 mins): [200 150 120 180]


**3. Split dataset into first half & second half**

In [6]:
part1, part2 = np.split(sessions,2)
print("First half sessions:", part1)
print("Second half sessions:", part2)

First half sessions: [ 45  60  30 200 150  20]
Second half sessions: [ 90 120  30  15  75 180]


**4. Concatenate reversed session + original**

In [8]:
combined = np.concatenate((sessions[::-1],sessions))
print("Concatenated reversed and original sessions:", combined)

Concatenated reversed and original sessions: [180  75  15  30 120  90  20 150 200  30  60  45  45  60  30 200 150  20
  90 120  30  15  75 180]
